version: "3.9"
services:
  chatgpt-next-web:
    container_name: chatgpt-next-web
    build:
      context: .
      dockerfile: Dockerfile
    image: xiaoguang-ai-fe
    env_file:
      - .env.local
    ports:
      - 3000:3000
